### ISSUE TITLE
Reloading Page and TextEditor is not loading

### ISSUE THREAD

**Issue by aqkhana2002** [aixasz/Blazeditor#8]
When i load page init , this is displaying the text Editor but when i reload page only i can see is Textbox.

any way to reload it ?

**Comment by aqkhana2002** [comment]
ok solved it by this way.

**created in _Host.chtml**
 function ReloadTinyMce(id) {
        tinymce.remove();
        tinymce.init();
    }

and calling this function in the page i am using like this

@inject BrowserService Service
protected override async Task OnInitializedAsync()
    {
        Service.ReloadTinyMce("demo");
    }


Service is basically an JSInterop to call method here is code for it 


using Microsoft.JSInterop;
using System.Threading.Tasks;

namespace ServerSideDemo.GlobalClass
{
    public class BrowserService
    {
        private readonly IJSRuntime _js;

        public BrowserService(IJSRuntime js)
        {
            _js = js;
        }

        public async Task<object> ReloadTinyMce(string id)
        {
            return await _js.InvokeAsync<object>("ReloadTinyMce", id);
        }
    }
}


in startup.cs you have to register it 

 services.AddScoped<BrowserService>();

**Comment by aixasz** [comment]
Nice catch, this was the good issue. I will take time to solve this and release in `1.0.3`. 

Thank you.

**Comment by aixasz** [comment]
Seems this was fixed in `1.0.2` you can double check it in sample project.

**Comment by SmRiley** [comment]
Still exists in the current version, v1.2.2 / server inside
